MultiLanguage/Models/ErrorViewModel.cs
namespace MultiLanguage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MultiLanguage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MultiLanguage.Models;
using System.Diagnostics;

namespace MultiLanguage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MultiLanguage/Controllers/UserManagerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MultiLanguage.Core.PublicClasses.Repository.Interfaces;
using MultiLanguage.Core.ViewModels;
using Multipisus.DataLayer.Entities;

namespace MultiLanguage.Controllers
{
    public class UserManagerController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly INotyfService _notify;
        private readonly IMapper _mapper;

        public UserManagerController(IUnitOfWork context,INotyfService noty , IMapper mapper)
        {
            _context = context;
            _notify = noty;
            _mapper = mapper;
        }

        //list of user
        public async Task<IActionResult> Index()
        {

            var user = await _context.UsermanagerUW.GetEntitiesAsync();
            return View(user);
        }
        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserViewModels model)
        {
            var user = new ApplicationUser
            {
              Name=model.Name,
              LastName=model.LastName,
              UserImg=model.UserImg,
              Department=model.Department,
              IsActive=model.IsActive,
              IsDelete = false,
            };
            await _context.UsermanagerUW.Create(user);
            await _context.saveAsync();
            _notify.Success("You successfuly Added  a new user !", 5);
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Detials(string id)
        {
            var user = await _context.UsermanagerUW.GetByIdAsync(id);
            return View(user);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _context.UsermanagerUW.GetByIdAsync(id);
            if (user.IsDelete)
            {
                ViewBag.Message = "You are actvating this Category!";
            }
            else
            {
                ViewBag.Message = "You are InActvating this Category! , you can always undo";
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                if (model.IsDelete)
                {
                    model.IsDelete = false;
                }
                else
                {
                    model.IsDelete = true;
                }
                _context.UsermanagerUW.Update(model);
                await _context.saveAsync();
                _notify.Success("You successfuly changed the user status   !", 5);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _context.UsermanagerUW.GetByIdAsync(id);
            var mapUser = _mapper.Map<UserViewModels>(user);
            return View(mapUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(UserViewModels model)
        {

          return View(model); 
        }


    }
}

MultiLanguage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p> Hi how are you this is the first project of my multulanguage project</p>
</div>

MultiLanguage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <!-- START - MetaTags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="fa">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MultiLanguage project</title>
    <!-- END - MetaTags -->
    <!-- START - stylesheets -->
    <link href="~/panel/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/panel/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/panel/assets/css/core.css" rel="stylesheet" type="text/css">
    <link href="~/panel/assets/css/components.css" rel="stylesheet" type="text/css">
    <link href="~/css/customStyle.css" rel="stylesheet" />
  
    <link href="~/lib/MdPersiandatetimepicker/css/jquery.Bootstrap-PersianDateTimePicker.css" rel="stylesheet" />
    <!--jstree css-->
    <link href="~/lib/jstree/dist/themes/default/style.css" rel="stylesheet" />
</head>

<body class="navbar-top">
    <!-- START - Main Navibar -->
    <partial name="_navbarPartial" />
    <!-- END - Main Navibar -->
    <!-- START - Main Content -->
    <div class="page-container">

        <!-- START - Page Content -->
        <div class="page-content">

            <!-- START - Main Sidebar -->
            <partial name="_SidebarPartial" />

            <!-- START - Main Content -->
            <div class="content-wrapper">

                <div class="content">

                    <!-- START - View Content -->
                    <div class="row">
                        @RenderBody()
                    </div>
                    <!-- END - View Content -->


                </div>
                <!-- /content area -->
            </div>
            <!-- END - Main Content -->

        </div>
        <!-- END - Page Content -->

    </div>
    <!-- END - Main Content -->
    <!--Top Loading-->
    <script type="text/javascript" src="~/panel/assets/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="~/panel/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/panel/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/panel/assets/js/plugins/ui/nicescroll.min.js"></script>
    <script type="text/javascript" src="~/panel/assets/js/core/app.js"></script>
    <script src="~/lib/MdPersiandatetimepicker/js/calendar.min.js"></script>
    <script src="~/lib/MdPersiandatetimepicker/js/jquery.Bootstrap-PersianDateTimePicker.min.js"></script>
    <script src="~/lib/jstree/dist/jstree.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
      @await Component.InvokeAsync("Notyf") 
    @RenderSection("AdminScripts", required: false)

</body>

</html>

MultiLanguage/Views/Shared/_SidebarPartial.cshtml
<div class="sidebar sidebar-main" style="background-color:#d4d1d1;">
    <div class="sidebar-content">

        <!-- START - User menu -->
      
        <!-- END - User menu -->
        <!-- START - Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">

                <!-- START - Item Navigation -->
                <ul class="navigation navigation-main" style="color:black;">

                    <!-- START - Item Navigation Header -->
                    <li class="navigation-header">
                        <span> داشبورد اختصاصی کاربران</span> <i class="icon-menu"
                                                                 title="صفحه اصلی"></i>
                    </li>

                    <li>
                        <a asp-controller="UserManager" asp-action="Index"><i class="icon-users"></i><span>مدیریت کاربران</span></a>
                    </li>
                    <li>
                        <a asp-controller="JobsChart" asp-action="Index"><i class="icon-office"></i><span>مشاغل</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-traffic-cone"></i><span>کنترل ورود و خروج</span></a>
                    </li>
                    <li>
                        <a asp-controller="UserJobManager" asp-action="Index"><i class="icon-office"></i><span>انتساب شغل</span></a>
                    </li>
                    <li>
                        <a asp-controller="News" asp-action="Index"><i class="icon-newspaper"></i><span>  اخبار و اطلاعیه ها </span></a>
                    </li>
                    <li>
                        <a asp-controller="AdministrativeForm" asp-action="Index"><i class="icon-forward3"></i><span>فرم های اداری</span></a>
                    </li>
                    <li>
                        <a asp-controller="Reminder" asp-action="Index"><i class="icon-reminder"></i><span>ثبت یادآوری</span></a>
                    </li>
                    <li>
                        <a asp-controller="SystemPart" asp-action="Index"><i class="icon-sync"></i><span>اجزای سیستم</span></a>
                    </li>
                    <li>
                        <a asp-controller="AccessRight" asp-action="Index"><i class="icon-accessibility"></i><span>کنترل دسترسی ها</span></a>
                    </li>
                    <li>
                        <a asp-controller="RolePattern" asp-action="Index"><i class="icon-accessibility2"></i><span>نقش های کاربری  </span></a>
                    </li>
                </ul>
                <!-- END - Item Navigation -->

            </div>
        </div>
        <!-- END - Main navigation -->

    </div>
</div>

MultiLanguage/Views/Shared/_navbarPartial.cshtml
<div class="navbar navbar-fixed-top" style="background-color:#9b9d9d;">
    <div class="navbar-header">
        <a class="navbar-brand" href="#"></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile" style="color:white;"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle" style="color:black;"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile" style="background-color:#9b9d9d;">
        <ul class="nav navbar-nav">
            <li>
                <a class="sidebar-control sidebar-main-toggle hidden-xs" style="color:black;"><i class="icon-paragraph-justify3"></i></a>
            </li>
        </ul>
        <form asp-area="" asp-controller="Account" asp-action="LogOut" method="post">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown dropdown-user">
                    <a class="dropdown-toggle" data-toggle="dropdown" style="color:black;">

                        <span>امکانات شخصی</span>
                        <i class="caret"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a href="#"><i class="icon-user-plus"></i>پروفایل من</a></li>
                        <li class="divider"></li>
                        <li><button type="submit" style="border:none; background-color:white"><i class="icon-switch2"></i> خروج از سیستم</button></li>
                    </ul>
                </li>
            </ul>
        </form>
    </div>
</div>

MultiLanguage/Views/UserManager/Index.cshtml
@model MultiLanguage.Core.PublicClasses
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var counter = 1;
}

<div class="content">
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span>
            <i class="glyphicon glyphicon-user"></i>
            لست کاربران سامانه
        </span>
    </div>
    <div style="margin-bottom:5px;">
        <a class="btn customGreen1" asp-controller="UserManager" asp-action="AddUser">
            <i class="glyphicon glyphicon-plus"></i>
            افزودن کاربر جدید
        </a>
    </div>

    <div>
        <div class=" table-responsive">
            <table class="table table-bordered table-hover table-striped" style="border-radius:2px; box-shadow:3px 3px 1px 0 gray;">
                <thead style="font-weight:bold;">
                    <tr>
                        <td>ردیف</td>
                        <td>نام</td>
                        <td>فامیلی</td>
                        <td>شماره تماس</td>
                        <td>کد پرسنلی</td>
                        <td>کد ملی</td>
                        <td> تصویر</td>
                        <td> امضا</td>
                        <td>وضعیت</td>
                        <td>نوع</td>
                        <td>عملیات</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr style="font-size:12px;">
                            <td style="width:40px; text-align:center;">@counter</td>
                            <td style="text-align:right;">@item.FirstName</td>
                            <td>@item.Family</td>
                            <td>@item.PhoneNumber</td>
                            <td>@item.personalCode</td>
                            <td>@item.MelliCode</td>
                            <td style="text-align:center; padding:2px;">
                                <img src="~/upload/userimage/@item.ImagePath" style="width:60px; height:65px;" />
                            </td>
                            <td style="text-align:center; padding:2px;">
                                <img src="~/upload/signatureimage/@item.SignaturePath" style="width:60px; height:65px;" />
                            </td>
                            @if (item.IsActive == 1)
                            {
                                <td style="width:35px; color:black;">
                                    <span class="badge badge-success" style="width:50px; border-radius:15px;">
                                        فعال
                                    </span>
                                </td>
                            }
                            else
                            {
                                <td style="width:35px; color:black;">
                                    <span class="badge badge-danger" style="width:50px; border-radius:15px;">
                                        غیر فعال
                                    </span>
                                </td>
                            }
                           <td>
                               @(item.IsAdmin==1 ? "ادمین" :"کاربر" )
                           </td>
                            <td>
                                <div class="row">
                                    <a asp-action="UserDetails" asp-controller="UserManager" asp-route-userId="@item.Id" style="width:65px; height:30px;
                                       font-size:10px; margin-bottom:3px; " class="btn customBlue1">
                                        <i class="glyphicon glyphicon-book"></i>
                                    </a>
                                    <a asp-controller="UserManager" asp-action="EditUser" asp-route-userId="@item.Id"
                                       style="height:30px; width:60px; font-size:9px; margin-bottom:3px;"
                                       class="btn customYellow1">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>

                                    @if (item.IsActive == 1)
                                    {
                                        <a asp-action="ActiveOrDeactiveUser" asp-controller="UserManager"
                                           asp-route-userID="@item.Id" asp-route-IsActive="@item.IsActive" data-toggle="modal" data-target="#modal-action" style="width:65px; height:30px;
                                       font-size:10px; margin-bottom:3px; " class="btn customRed1 ">
                                            <i class="glyphicon glyphicon-remove"></i>
                                        </a>

                                    }
                                    else
                                    {
                                        <a asp-action="ActiveOrDeactiveUser" asp-controller="UserManager" asp-route-userID="@item.Id" asp-route-IsActive="@item.IsActive" data-toggle="modal" data-target="#modal-action"
                                           style="width:65px; height:30px;
                                       font-size:10px; margin-bottom:3px; " class="btn customGreen1 ">
                                            <i class="glyphicon glyphicon-ok"></i>
                                        </a>
                                    }
                                    <a asp-action="ChangePasswordByAdmin" asp-controller="UserManager" 
                                       asp-route-UserId="@item.Id"
                                       asp-route-FullName="@item.FirstName @item.Family"
                                       data-toggle="modal" data-target="#modal-action"
                                       style="width:65px; height:30px;
                                       font-size:10px; margin-bottom:3px; " class="btn customGreen1 ">
                                        <i class="icon-key"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        counter++;
                    }
                </tbody>
            </table>
        </div>
    </div>


</div>
@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action", Size = BootstrapModel.ModalSize.Large })

@section AdminScripts {
   <script src="~/js/modal/modal.js"></script>
    }